#! /bin/bash

display_usage() {
   echo -e "Usage: \n bla bla bla... \n"
}

### Commands ------------------------------

export AVAILABLE_COMMANDS=(start_all start_processes stop clean restart resize get exit)

# In order to insert a new command, add it to the previus array
# and create a new function called cmd_NAME

# Controlled exit
cmd_exit(){
   exit 0
}

# create_cluster
cmd_create_cluster(){
    echo "Creating a new cluster"
    gcloud container clusters create cl1 --num-nodes=2
}

# start_processes
cmd_start_processes(){
   echo "Starting kubernetes processes"
   
   cd kubernetes
    
   # mongo, grade and api server
   # sleep are added in order to give time to the db to start
   sleep 1
   kubectl create -f db.yml
   sleep 5
   kubectl create -f grade.yml
   sleep 2
   kubectl create -f web.yml

}

# start_all
cmd_start_all(){
   cmd_create_cluster
   cmd_start_processes
}

# clean
cmd_clean(){
   echo "Cleaning kubernetes processes"

   # Clean deploy, svc, rc and pods
   kubectl delete deploy --all
   kubectl delete svc --all
   kubectl delete rc --all
   kubectl delete po --all
}

# stop
cmd_stop(){
   echo "Stopping the cluster"
   
   cmd_clean
   
   # Tear down the cluster
   gcloud container clusters delete cl1
   
}

# restart
cmd_restart(){
   echo "Restarting the cluster"
   cmd_clean
   sleep 35
   cmd_start_processes 
}

# resize
cmd_resize(){
   echo "Resizing deployment of..."

   # DISPLAY DEPLOYMENTS
   for option in ${DEPLOYMENTS_PROD[*]};
   do
      echo "- $option"
   done
}

cmd_external-ip(){
   kubectl get svc | awk -F" " '$3~/^[0-9]/ {print $1,$3}'
}

# get
cmd_get(){
   GET_OPTIONS_LIST=(external-ip exit)
   clear
   echo "Available cluster info"
   # if option in GET_OPTIONS_LIST, switch 
   # Display commands and let user choose
   while : ;
   do
       echo "Choose a command using its number:"
       for ((i=1;i <= ${#GET_OPTIONS_LIST[@]}; i++));
       do
           echo $i. ${GET_OPTIONS_LIST[i-1]}
       done
       read choice
       if [[ $choice =~ ^[0-9]+$ && ${choice} -gt 0 && ${choice} -lt ${#GET_OPTIONS_LIST[@]}+1 ]]
       then
           CHOSEN_OPTION=${GET_OPTIONS_LIST[$choice-1]/.\//}
           break
       else
          clear
          echo -e "Unrecognized command. Type a number among the one shown below.\n"
       fi
   done
   
   cmd_$CHOSEN_OPTION
}

# -----------------------------------------
