#! /bin/bash

IMAGE_NAME=$(basename "$PWD")
# Using the seconds since 1970-01-01 00:00:00 UTC as image tag
IMAGE_TAG=$(date +'%s')
IMAGE_NAME+=":${IMAGE_TAG}"
CONTAINER_NAME="${DEV_USER}/${IMAGE_NAME}"
